In [1]:
#Q1 - Arrays
import numpy as np
def arrays(arr):
    arr =  np.flip(arr)
    arr  = arr.astype('float64')
    return arr
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5
[5. 4. 3. 2. 1.]


In [2]:
#Q2 - Shape & Reshape
import numpy as np
arr = input().strip().split(' ')
arr = np.reshape(arr,(3,3))
arr = arr.astype('int64')
print(arr)


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#Q3 - Transpose & Flatten
import numpy as np
n , m = input().split();
arr = [];
for i in range(int(n)):
    inp = input().split();
    arr.append(inp);
arr = np.array(arr,int);

print(np.transpose(arr))
print(arr.flatten())


2 2
1 2 
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [4]:
#Q4 - Concatenate
import numpy as np
N,M,P = map(int,input().split())
arr1 = np.array([input().split() for _ in range(N)],int)
arr2 = np.array([input().split() for _ in range(M)],int)
print(np.concatenate((arr1, arr2), axis = 0))



3 3 3
1 2 3
4 5 6
7 8 9
1 2 3
4 5 6
7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#Q5  - Zeros & Ones
import numpy as np
arr = list(map(int, input().split()))
print( np.zeros((arr), dtype = np.int))
print (np.ones((arr), dtype = np.int))





2 2
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]


In [6]:
#Q6 - Identity and Eye
import numpy as np
np.set_printoptions(legacy='1.13')
n,m = map(int, input().split())
print(np.eye(n,m))




3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [7]:
#Q7 - Array Maths
import numpy as np
N,M = map(int,input().split())
A = np.array([input().split() for _ in range(N)],int)
B = np.array([input().split() for _ in range(N)],int)
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)


2 2
1 2
3 4
5 6 
7 8
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0 0]
 [0 0]]
[[1 2]
 [3 4]]
[[    1    64]
 [ 2187 65536]]


In [8]:
#Q8 - Floor,Ceil,Rint
import numpy as np
np.set_printoptions(legacy='1.13')
arr = np.array(input().split(),float)
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))


1.1 2.2 4.6
[ 1.  2.  4.]
[ 2.  3.  5.]
[ 1.  2.  5.]


In [11]:
#Q9 - Sum & Prod
import numpy as np
N,M = map(int,input().split())
arr = np.array([input().split() for _ in range(N)],int)
x = np.sum(arr,axis = 0)
print(np.prod(x))



2 2 
2 3
4 5
48


In [12]:
#Q10 - Min and Max
import numpy as np
N,M = map(int,input().split())
arr = np.array([input().split() for _ in range(N)],int)
x = np.min(arr,axis = 1)
print(np.max(x))


2 2
1 2
3 4
3


In [15]:
#Q11 - Mean, Variance, Std Deviation
import numpy as np
N,M = map(int,input().split())
arr = np.array([input().split() for _ in range(N)],int)
print(np.mean(arr,axis = 1))
print(np.var(arr,axis=0))
print(round(np.std(arr,axis=None),11))






2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [17]:
#Q12 - dot and cross
import numpy as np
N = int(input())
A = np.array([input().split() for _ in range(N)],int)
B = np.array([input().split() for _ in range(N)],int)
print(np.dot(A,B))




2
1 2
1 2
1 2
1 2
[[3 6]
 [3 6]]


In [18]:
#Q13 - Inner & Outer
import numpy as  np
A = np.array(input().split(),int)
B = np.array(input().split(),int)
print(np.inner(A,B))
print(np.outer(A,B))

1 2 3
3 4 6
29
[[ 3  4  6]
 [ 6  8 12]
 [ 9 12 18]]


In [19]:
#Q14 - Polynomials
import numpy as np

A = np.array(input().split(),float)
x  = int(input())
print(np.polyval(A,x))


1 2 3 4 5 6
2
120.0


In [22]:
#Q15 - Linear Algebra
import numpy as np
N = int(input())
A = np.array([input().split() for _ in range(N)],float)
print(round(np.linalg.det(A),2))





2 
1.1 3.4
2.2 7
0.22
